featured:
  - name: TED Global
    keyword: ted
  - name: Youtube Playlist Store
    keyword: playlist-store
  - name: Nike Running
    keyword: nike
  - name: Loggi
    keyword: loggi
  - name: Grow With Us
    keyword: gwu
