featured:
  - name: TED Global
    keyword: ted
  - name: Youtube Playlist Store
    keyword: playlist-store
  - name: Nike Running
    keyword: nike
  - name: Read for a Child
    keyword: itau-crianca
  - name: Grow With Us
    keyword: gwu
